// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uenphmufgglhedwmacnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbnBobXVmZ2dsaGVkd21hY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODE3MDAsImV4cCI6MjA2Njc1NzcwMH0.3Q2hTZZhOgwhIXdYjh0XdaH2uSHQk91c2V2e18vt9fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);